version: "2"
services:
  api:
    build: ./api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 4001:4000
  front:
    build: ./front
    ports:
      - 4000:4000
    depends_on:
      - api
